# =============================================================================
# Let's Encrypt ClusterIssuers
# =============================================================================
# cert-manager ClusterIssuers for automatic TLS certificate management
# Applied after cert-manager is installed (sync wave -1)
# =============================================================================
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/part-of: autogit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  acme:
    # Staging server for testing (no rate limits)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tz-dev@vectorweight.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/part-of: autogit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  acme:
    # Production server (rate limited)
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tz-dev@vectorweight.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: traefik
