# =============================================================================
# Resource Quotas
# =============================================================================
# Resource quotas to prevent runaway resource usage
# =============================================================================
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: autogit-runners-quota
  namespace: autogit-runners
  labels:
    app.kubernetes.io/part-of: autogit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "50"
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: autogit-runners-limits
  namespace: autogit-runners
  labels:
    app.kubernetes.io/part-of: autogit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  limits:
    - default:
        cpu: "2"
        memory: 2Gi
      defaultRequest:
        cpu: "500m"
        memory: 512Mi
      type: Container
    - max:
        cpu: "8"
        memory: 16Gi
      min:
        cpu: "100m"
        memory: 128Mi
      type: Container
