---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  comments:
    min-spaces-from-content: 1

  indentation:
    spaces: 2
    indent-sequences: true

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

ignore: |
  .git/
  node_modules/
  venv/
