# =============================================================================
# Staging Environment Values
# =============================================================================
# Configuration for staging environment
# =============================================================================

global:
  domain: staging.autogit.local
  clusterIssuer: letsencrypt-staging
  storageClass: ""

resources:
  profile: minimal

features:
  monitoring: true
  logging: true
  tracing: false
  registry: false
